import { type Company } from './company-format'

export const mockCompanies: Company[] = [
  {
    slug: 'openai',
    name: 'OpenAI',
    initials: 'OA',
    logoTone: 'green',
    tagline: 'Creating safe AGI that benefits all of humanity.',
    description: 'OpenAI is an AI research and deployment company behind GPT-4o, ChatGPT, Sora, and DALL-E, advancing artificial general intelligence through foundational multi-modal research.',
    country: 'United States',
    founded: 2015,
    sector: 'Foundation Models',
    type: 'Private',
    categories: ['Foundation Models', 'Generative AI', 'AI Native', 'Unicorns', 'Model Companies'],
    valuation: 157000,
    employees: 1750,
    models: 42,
    tools: 18,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://openai.com',
    products: ['ChatGPT', 'GPT-4o', 'DALL-E 3', 'Sora', 'OpenAI API', 'Codex', 'Whisper']
  },
  {
    slug: 'anthropic',
    name: 'Anthropic',
    initials: 'AN',
    logoTone: 'orange',
    tagline: 'AI research company dedicated to building safe, steerable systems.',
    description: 'Anthropic is an AI safety and research company that builds reliable, interpretable, and steerable AI systems including Claude 3.5 Sonnet, Claude 3 Opus, and constitutional AI architectures.',
    country: 'United States',
    founded: 2021,
    sector: 'Foundation Models',
    type: 'Private',
    categories: ['Foundation Models', 'AI Model Providers', 'AI Native', 'Unicorns', 'Model Companies'],
    valuation: 40000,
    employees: 850,
    models: 28,
    tools: 12,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://anthropic.com',
    products: ['Claude 3.5 Sonnet', 'Claude 3 Opus', 'Claude 3.5 Haiku', 'Claude Artifacts', 'Anthropic API']
  },
  {
    slug: 'deepseek',
    name: 'DeepSeek',
    initials: 'DS',
    logoTone: 'blue',
    tagline: 'Unraveling the mystery of AGI with open-weight frontier models.',
    description: 'DeepSeek is an open research collective and AI enterprise pioneering ultra-efficient Mixture-of-Experts architectures, reasoning models like DeepSeek-R1, and DeepSeek-V3.',
    country: 'China',
    founded: 2023,
    sector: 'Open Source',
    type: 'Private',
    categories: ['Open Source', 'Foundation Models', 'AI Native', 'Developer Tools', 'Model Companies'],
    valuation: 12000,
    employees: 200,
    models: 16,
    tools: 9,
    aiNative: true,
    profitable: true,
    verified: true,
    website: 'https://deepseek.com',
    products: ['DeepSeek-R1', 'DeepSeek-V3', 'DeepSeek-Coder', 'DeepSeek-Math', 'DeepSeek API']
  },
  {
    slug: 'mistral-ai',
    name: 'Mistral AI',
    initials: 'MS',
    logoTone: 'yellow',
    tagline: 'Frontier AI in your hands — open, efficient, European.',
    description: 'Mistral AI develops leading open-weight and proprietary language models including Mistral Large, Pixtral, Codestral, and Le Chat, focusing on European sovereignty and open science.',
    country: 'France',
    founded: 2023,
    sector: 'Foundation Models',
    type: 'Private',
    categories: ['Foundation Models', 'Open Source', 'AI Native', 'Unicorns', 'Developer Tools'],
    valuation: 6200,
    employees: 160,
    models: 19,
    tools: 8,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://mistral.ai',
    products: ['Mistral Large 2', 'Codestral', 'Pixtral', 'Le Chat', 'La Plateforme', 'Mistral NeMo']
  },
  {
    slug: 'perplexity',
    name: 'Perplexity AI',
    initials: 'PX',
    logoTone: 'violet',
    tagline: 'Where knowledge begins — interactive conversational answer engine.',
    description: 'Perplexity AI builds an AI-powered conversational answer and search engine that delivers real-time citations, multi-model query synthesis, and deep research assistants.',
    country: 'United States',
    founded: 2022,
    sector: 'Generative AI',
    type: 'Private',
    categories: ['Generative AI', 'Enterprise', 'AI Native', 'Unicorns', 'Personal'],
    valuation: 9000,
    employees: 240,
    models: 14,
    tools: 22,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://perplexity.ai',
    products: ['Perplexity Pro', 'Perplexity Pages', 'Sonar API', 'Perplexity Collections', 'Enterprise Pro']
  },
  {
    slug: 'xai',
    name: 'xAI',
    initials: 'xA',
    logoTone: 'slate',
    tagline: 'Understand the universe through frontier artificial intelligence.',
    description: 'xAI builds Grok models on the Colossus supercomputer cluster to accelerate scientific discovery, real-time multimodal reasoning, and deep cosmological comprehension.',
    country: 'United States',
    founded: 2023,
    sector: 'Foundation Models',
    type: 'Private',
    categories: ['Foundation Models', 'AI Native', 'Unicorns', 'Model Companies'],
    valuation: 50000,
    employees: 400,
    models: 12,
    tools: 6,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://x.ai',
    products: ['Grok 2', 'Grok 2 Vision', 'Grok API', 'Colossus Supercluster']
  },
  {
    slug: 'cohere',
    name: 'Cohere',
    initials: 'CO',
    logoTone: 'pink',
    tagline: 'Enterprise AI platform for search, discovery, and generation.',
    description: 'Cohere builds multilingual enterprise language models, industry-standard RAG re-rankers, and Command R+ models optimized for private clouds and secure corporate data.',
    country: 'Canada',
    founded: 2019,
    sector: 'Enterprise',
    type: 'Private',
    categories: ['Enterprise', 'Developer Tools', 'AI Native', 'Unicorns', 'AI Model Providers'],
    valuation: 5500,
    employees: 450,
    models: 22,
    tools: 15,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://cohere.com',
    products: ['Command R+', 'Command R', 'Cohere Rerank', 'Embed v3', 'Cohere Compass']
  },
  {
    slug: 'cursor-anysphere',
    name: 'Cursor (Anysphere)',
    initials: 'CR',
    logoTone: 'blue',
    tagline: 'The AI-first code editor designed for pair-programming at lightspeed.',
    description: 'Cursor is an AI-first IDE fork of VS Code built by Anysphere that transforms software engineering with autonomous multi-file edits, codebase indexing, and tab-autocomplete.',
    country: 'United States',
    founded: 2022,
    sector: 'Developer Tools',
    type: 'Private',
    categories: ['Developer Tools', 'AI Native', 'Unicorns', 'Generative AI'],
    valuation: 2500,
    employees: 60,
    models: 8,
    tools: 14,
    aiNative: true,
    profitable: true,
    verified: true,
    website: 'https://cursor.com',
    products: ['Cursor Editor', 'Composer Agent', 'Copilot++ Auto-suggest', 'Codebase Indexing']
  },
  {
    slug: 'scale-ai',
    name: 'Scale AI',
    initials: 'SC',
    logoTone: 'purple',
    tagline: 'The data foundry powering frontier generative AI models.',
    description: 'Scale AI provides data infrastructure, human-in-the-loop fine-tuning (RLHF), evaluation benchmarks (SEAL), and enterprise generative platforms for military and commercial leaders.',
    country: 'United States',
    founded: 2016,
    sector: 'Infrastructure',
    type: 'Private',
    categories: ['Infrastructure', 'Enterprise', 'AI Native', 'Unicorns'],
    valuation: 13800,
    employees: 1200,
    models: 15,
    tools: 26,
    aiNative: true,
    profitable: true,
    verified: true,
    website: 'https://scale.com',
    products: ['Scale GenAI Platform', 'Scale Data Foundry', 'SEAL Leaderboards', 'Scale Donovan']
  },
  {
    slug: 'hugging-face',
    name: 'Hugging Face',
    initials: 'HF',
    logoTone: 'yellow',
    tagline: 'The open-source AI community hub, model repository, and compute platform.',
    description: 'Hugging Face is the central collaboration platform for machine learning, hosting over 1,000,000 open-source models, datasets, Spaces demo apps, and inference endpoints.',
    country: 'United States',
    founded: 2016,
    sector: 'Open Source',
    type: 'Private',
    categories: ['Open Source', 'Developer Tools', 'Infrastructure', 'Unicorns'],
    valuation: 4500,
    employees: 280,
    models: 85,
    tools: 45,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://huggingface.co',
    products: ['Hugging Face Hub', 'Transformers', 'Spaces', 'Inference Endpoints', 'TGI (Text Gen Inference)', 'Datasets']
  },
  {
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    initials: 'EL',
    logoTone: 'orange',
    tagline: 'Voice AI research and realistic audio generation.',
    description: 'ElevenLabs develops industry-leading synthetic voice synthesis, dubbing, sound effects, and real-time conversational voice agents across 32+ languages.',
    country: 'United States',
    founded: 2022,
    sector: 'Generative AI',
    type: 'Private',
    categories: ['Generative AI', 'Creativity', 'AI Native', 'Unicorns'],
    valuation: 3300,
    employees: 140,
    models: 18,
    tools: 16,
    aiNative: true,
    profitable: true,
    verified: true,
    website: 'https://elevenlabs.io',
    products: ['VoiceLab', 'Conversational AI Agent', 'AI Dubbing Studio', 'Sound Effects Engine', 'Reader App']
  },
  {
    slug: 'runway',
    name: 'Runway',
    initials: 'RW',
    logoTone: 'pink',
    tagline: 'Advancing creativity with general world models and AI video.',
    description: 'Runway develops multimodal generative video systems including Gen-3 Alpha, empowering filmmakers, studios, and creators with cinematic world-simulation tools.',
    country: 'United States',
    founded: 2018,
    sector: 'Generative AI',
    type: 'Private',
    categories: ['Generative AI', 'Creativity', 'AI Native', 'Unicorns'],
    valuation: 3000,
    employees: 180,
    models: 16,
    tools: 20,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://runwayml.com',
    products: ['Gen-3 Alpha', 'Gen-2', 'Motion Brush', 'Camera Control', 'Runway Studios']
  },
  {
    slug: 'midjourney',
    name: 'Midjourney',
    initials: 'MJ',
    logoTone: 'violet',
    tagline: 'An independent research lab exploring new mediums of thought.',
    description: 'Midjourney is a self-funded research lab that creates state-of-the-art AI image generation models and web canvas interfaces used by tens of millions worldwide.',
    country: 'United States',
    founded: 2021,
    sector: 'Generative AI',
    type: 'Private',
    categories: ['Generative AI', 'Creativity', 'AI Native'],
    valuation: 10000,
    employees: 110,
    models: 12,
    tools: 8,
    aiNative: true,
    profitable: true,
    verified: true,
    website: 'https://midjourney.com',
    products: ['Midjourney v6.1', 'Midjourney Web Editor', 'Inpainting & Outpainting', 'Style Reference']
  },
  {
    slug: 'groq',
    name: 'Groq',
    initials: 'GQ',
    logoTone: 'orange',
    tagline: 'Ultra-low latency LPU Inference Engine for real-time AI.',
    description: 'Groq designs custom Language Processing Unit (LPU) silicon hardware and cloud APIs delivering hundreds of tokens per second for real-time language model execution.',
    country: 'United States',
    founded: 2016,
    sector: 'Infrastructure',
    type: 'Private',
    categories: ['Infrastructure', 'Developer Tools', 'Unicorns', 'AI Native'],
    valuation: 2800,
    employees: 320,
    models: 14,
    tools: 10,
    aiNative: false,
    profitable: false,
    verified: true,
    website: 'https://groq.com',
    products: ['GroqCloud API', 'Groq LPU Silicon', 'GroqRack', 'GroqChat']
  },
  {
    slug: 'together-ai',
    name: 'Together AI',
    initials: 'TG',
    logoTone: 'blue',
    tagline: 'The fastest cloud platform for training and serving open-source AI.',
    description: 'Together AI is a cloud infrastructure provider optimizing GPU clusters, custom FlashAttention kernels, and high-throughput inference for open-source AI models.',
    country: 'United States',
    founded: 2022,
    sector: 'Infrastructure',
    type: 'Private',
    categories: ['Infrastructure', 'Open Source', 'Developer Tools', 'AI Native', 'Unicorns'],
    valuation: 1300,
    employees: 130,
    models: 24,
    tools: 12,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://together.ai',
    products: ['Together Inference Engine', 'Custom Cluster GPU Cloud', 'RedPajama Datasets', 'Together Fine-tuning']
  },
  {
    slug: 'harvey',
    name: 'Harvey',
    initials: 'HV',
    logoTone: 'slate',
    tagline: 'Generative AI platform custom-built for legal and professional services.',
    description: 'Harvey partners with top global law firms and corporate legal departments to automate contract analysis, litigation drafting, due diligence, and regulatory compliance.',
    country: 'United States',
    founded: 2022,
    sector: 'Enterprise',
    type: 'Private',
    categories: ['Enterprise', 'AI Native', 'Unicorns', 'Finance'],
    valuation: 1500,
    employees: 180,
    models: 8,
    tools: 14,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://harvey.ai',
    products: ['Harvey Legal Assistant', 'Vault Document Intelligence', 'Contract Reviewer', 'Harvey API']
  },
  {
    slug: 'cognition',
    name: 'Cognition',
    initials: 'CG',
    logoTone: 'green',
    tagline: 'Applied AI lab creating Devin, the first autonomous AI software engineer.',
    description: 'Cognition builds autonomous AI teammates capable of planning, executing complex engineering projects, debugging codebases, and submitting pull requests.',
    country: 'United States',
    founded: 2023,
    sector: 'Developer Tools',
    type: 'Private',
    categories: ['Developer Tools', 'Agents', 'AI Native', 'Unicorns'],
    valuation: 2000,
    employees: 45,
    models: 6,
    tools: 10,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://cognition.ai',
    products: ['Devin AI Engineer', 'Cognition Enterprise Platform']
  },
  {
    slug: 'synthesia',
    name: 'Synthesia',
    initials: 'SY',
    logoTone: 'purple',
    tagline: 'Turn text into professional studio-grade AI video avatars in minutes.',
    description: 'Synthesia is an enterprise AI video generation platform creating photorealistic digital human avatars and automated multi-language video localization.',
    country: 'United Kingdom',
    founded: 2017,
    sector: 'Marketing',
    type: 'Private',
    categories: ['Marketing', 'Enterprise', 'Generative AI', 'Unicorns'],
    valuation: 1000,
    employees: 340,
    models: 15,
    tools: 18,
    aiNative: true,
    profitable: true,
    verified: true,
    website: 'https://synthesia.io',
    products: ['Synthesia Studio', 'Expressive Avatars', 'AI Video Assistant', 'Custom Avatar Generator']
  },
  {
    slug: 'figure-ai',
    name: 'Figure AI',
    initials: 'FG',
    logoTone: 'cream',
    tagline: 'Autonomous humanoid robots designed for commercial and industrial labor.',
    description: 'Figure AI develops general-purpose humanoid robots integrated with neural network vision-language models for dexterous manipulation and warehouse deployment.',
    country: 'United States',
    founded: 2022,
    sector: 'Robotics',
    type: 'Private',
    categories: ['Robotics', 'Devices', 'AI Native', 'Unicorns'],
    valuation: 2600,
    employees: 160,
    models: 9,
    tools: 7,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://figure.ai',
    products: ['Figure 02 Humanoid', 'Neural Task Engine', 'Fleet Operations Manager']
  },
  {
    slug: 'character-ai',
    name: 'Character.ai',
    initials: 'CA',
    logoTone: 'pink',
    tagline: 'Personalized AI companions and conversational agents.',
    description: 'Character.ai creates interactive conversational AI agents with distinct personalities, memories, and voice synthesizers used by millions of daily active users.',
    country: 'United States',
    founded: 2021,
    sector: 'Generative AI',
    type: 'Private',
    categories: ['Generative AI', 'Personal', 'AI Native', 'Unicorns'],
    valuation: 2500,
    employees: 140,
    models: 12,
    tools: 15,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://character.ai',
    products: ['Character.ai Chat', 'c.ai Voices', 'Character Group Chat', 'Persona Engine']
  },
  {
    slug: 'insilico-medicine',
    name: 'Insilico Medicine',
    initials: 'IM',
    logoTone: 'green',
    tagline: 'End-to-end generative AI drug discovery and longevity biotechnology.',
    description: 'Insilico Medicine applies generative chemistry, target identification, and clinical trial prediction to accelerate drug discovery from target to phase II trials.',
    country: 'United States',
    founded: 2014,
    sector: 'Healthcare',
    type: 'Private',
    categories: ['Healthcare', 'Enterprise', 'AI Native'],
    valuation: 1100,
    employees: 300,
    models: 20,
    tools: 16,
    aiNative: true,
    profitable: false,
    verified: true,
    website: 'https://insilico.com',
    products: ['Pharma.AI', 'PandaOmics', 'Chemistry42', 'inClinico']
  },
  {
    slug: 'databricks',
    name: 'Databricks',
    initials: 'DB',
    logoTone: 'orange',
    tagline: 'The unified data intelligence and enterprise machine learning platform.',
    description: 'Databricks unifies data engineering, analytics, and generative AI models with Mosaic AI, Apache Spark, and open-source DBRX foundation models.',
    country: 'United States',
    founded: 2013,
    sector: 'Infrastructure',
    type: 'Private',
    categories: ['Infrastructure', 'Enterprise', 'Developer Tools', 'Unicorns', 'AI Model Providers'],
    valuation: 43000,
    employees: 7000,
    models: 35,
    tools: 52,
    aiNative: false,
    profitable: true,
    verified: true,
    website: 'https://databricks.com',
    products: ['Mosaic AI', 'DBRX Foundation Model', 'Unity Catalog', 'Lakehouse Platform', 'MLflow']
  }
]
